"""Add foreign key to student model

Revision ID: e20251fc90a6
Revises: d0195f6806c5
Create Date: 2025-09-21 13:24:03.009556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20251fc90a6'
down_revision = 'd0195f6806c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creacted_by_user', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['creacted_by_user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creacted_by_user')

    # ### end Alembic commands ###
